export enum AUTH_CONSTANTS {
    LOGIN = "auth/LOGIN",
    LOGIN_SUCCESS = "auth/LOGIN_SUCCESS",
    LOGIN_FAILED = "auth/LOGIN_FAILED",

    REGISTER = "auth/REGISTER",
    REGISTER_SUCCESS = "auth/REGISTER_SUCCESS",
    REGISTER_FAILED = "auth/REGISTER_FAILED",

    PASSWORD_RECOVERY = "auth/PASSWORD_RECOVERY",
    PASSWORD_RECOVERY_SUCCESS = "auth/PASSWORD_RECOVERY_SUCCESS",
    PASSWORD_RECOVERY_FAILED = "auth/PASSWORD_RECOVERY_FAILED",
}
